### ISSUE TITLE
Anchor Links do not work

### ISSUE THREAD

**Issue by hazmeister** [SeleniumHQ/docs#141] opened 2017-09-21 21:11 UTC
Direct links to headings do not work on first load, but do once the page is loaded in the tab.

**Comment by Ravichandra-C** [comment] 2017-10-17 16:52
Can I take this up?

**Comment by diemol** [comment] 2019-03-17 22:27
@hazmeister is this still an issue? I was trying the PR that should be fixing it but I could not see the error. Perhaps I didn't really understand what is going on.

If the issue is still there, could you please give an example?

**Comment by hazmeister** [comment] 2019-03-18 07:42
@diemol It’s fiddly to test, but take a link to an anchor link (like waits on the webdriver page, as that’s quite far down the page). Then open that in a browser with a clean cache (as though you shared the link on slack with someone asking for help who hadn’t used the docs yet). Because we dynamically add and hide content which changes the height of the page, you don’t seem to end up in the right place. Seems to be ok once you have a cached copy of the page.

I don’t recall why, but testing that PR using webstorm wasn’t ideal, so I meant to take a look at it using Nginx as a local web server, but never got round to it. But I think that pr has good chances of remedying the issue.

**Comment by diemol** [comment] 2019-03-22 20:58
I get what you mean, then the PR is not fixing it.

**Comment by diemol** [comment] 2019-07-30 04:12
Closing as fixed after implementing the new docs UI powered by [Hugo](https://gohugo.io/)

**Closed as completed by diemol** 2019-07-30 04:12 UTC
